addSbtPlugin("org.jetbrains" % "sbt-ide-settings" % "1.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "1.0.0")
addSbtPlugin("com.github.sbt" % "sbt-release" % "1.1.0")
addSbtPlugin("me.pdalpra" % "sbt-autoversion" % "2.0.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.2")
//addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.1.0")
//addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.4")